<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\Identity\Common\" />
    <Folder Include="Features\TrueOrFalseQuestionAnswers\Handler\Commands\" />
    <Folder Include="Features\TrueOrFalseQuestionAnswers\Handler\Queries\" />
    <Folder Include="Features\TrueOrFalseQuestionAnswers\Request\Commands\" />
    <Folder Include="Features\TrueOrFalseQuestionAnswers\Request\Queries\" />
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OnlineExam.Domain\OnlineExam.Domain.csproj" />
  </ItemGroup>

</Project>
